### ISSUE TITLE
Remove comparison to “flat design”

### ISSUE THREAD

**Issue by jordanekay** [mds/good-button#1]
The README describes Good Button’s design as “flat(ish).” However, and thankfully, the actual approach taken has nothing in common with and in fact goes against the philosophy of flat design. I’d recommend removing references to that paradigm to avoid confusion.

**Comment by elischiff** [comment]
+1

**Comment by elischiff** [comment]
:+1:

**Comment by mds** [comment]
Good call. Fixed. =)
